### ISSUE TITLE
Coloring of tables is broken

### ISSUE THREAD

**Issue by Zethson** [MrDogeBro/sphinx_rtd_dark_mode#13]
Hi,

I have a rst table that I created with:

```
    +------------+------------+------------------------------+
    | Organism   | Tissue     | Marker File                  |
    +============+============+==============================+
    | Mouse      | Lung       | lung_particle_markers.txt    |
    +------------+------------+------------------------------+
    | Human      | NA         |                              |
    +------------+------------+------------------------------+
```

It gets rendered as
![image](https://user-images.githubusercontent.com/21954664/119802984-54863c80-bedf-11eb-98f4-0ef0f5913b83.png)

which is unreadable. There also shouldn't be any white. 

Link to docs: https://sc-toolbox.readthedocs.io/en/latest/usage.html#sc_toolbox.api.calc.automated_marker_annotation if it helps.

Thank you very much!

**Comment by MrDogeBro** [comment]
Hmm.....ok.....yeah thats something that I need to fix. Thanks for reporting that.
