### ISSUE TITLE
4th nested level for navigation bar white by default

### ISSUE THREAD

**Issue by Zethson** [MrDogeBro/sphinx_rtd_dark_mode#22]
Hi,

the fourth level of the navigation bar seem to be white by default and only get black on hover.
![issue_dark_sphinx](https://user-images.githubusercontent.com/21954664/122883692-bc447180-d33d-11eb-9bbd-ece8aa6220f0.gif)

I would be very happy if it weren't white by default since this is unreadable.

Thank you very much.
Cheers

**Comment by MrDogeBro** [comment]
Yeah that would be a bug there.....thanks.....
