### ISSUE TITLE
Disable animation/transition?

### ISSUE THREAD

**Issue by eerimoq** [MrDogeBro/sphinx_rtd_dark_mode#24]
Hi, nice job with the package!

Is it possible to disable the animation/transition when changing theme? It is not very smooth on my PC. I would prefer an immediate transition.

/ Erik

**Comment by MrDogeBro** [comment]
What do you mean by it is not very smooth?

**Comment by eerimoq** [comment]
Maybe it's my PC that is slow, but the transition from light to dark (and vice versa) is like 2 fps and not very pretty. I noticed that it looks good on my faster PC. It's not a big deal. I can live with it.

**Comment by mrelbe1** [comment]
Transitions are very smooth on my 'old' laptop and looks really nice (HP EliteBook 850 G6, i7-8665U @ 1.90GHz)
