### ISSUE TITLE
Pass custom dark css file to sphinx: Feature request 

### ISSUE THREAD

**Issue by rohit-kumar-j** [MrDogeBro/sphinx_rtd_dark_mode#33]
Pass [`custom_dark.css`](https://github.com/MrDogeBro/sphinx_rtd_dark_mode/tree/main/sphinx_rtd_dark_mode/static/dark_mode_css) file to sphinx, instead of dark.css

**Comment by MrDogeBro** [comment]
The ability to customize themes is already planned for v2.0.0 and will hopefully be out soon (#17).
