### ISSUE TITLE
Enhance dark theme and increase contrast for few stlyes

### ISSUE THREAD

**Issue by KrishnanSG** [MrDogeBro/sphinx_rtd_dark_mode#6]
@MrDogeBro 
Came across this repo yesterday and this exactly what I was looking for.
Great work and thanks for making it 🎉

Could you please look into the below issue and fix it. I want to push my docs to production soon but blocked with this issue and the dark theme at few places isn't looking great.

Ex:
In the below snap the contrast of Danger isn't good, also the dark theme seems to be too dark. 
![image](https://user-images.githubusercontent.com/43802499/118386543-c6d06480-b635-11eb-8125-7beaebfdd95d.png)

It would be great if you could have a dark theme similar to [mkdocs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)

**Comment by MrDogeBro** [comment]
@KrishnanSG thanks for reporting the error. I just need to make the danger get converted to dark mode so thank you for reporting that. On the topic of the dark theme being too dark, I would disagree. I personally like a very dark dark mode but I see where your coming from. Maybe I could add a option in the config that would allow you to select from multiple different dark themes. What do you think about that?

**Comment by MrDogeBro** [comment]
@KrishnanSG v1.1.2 has been released to fix the bug where the danger directive was not converted to dark mode.

**Comment by MrDogeBro** [comment]
@KrishnanSG the discussion about the dark mode amount and the possibility of having multiple different dark mode themes has been moved to a GitHub discussion (#8). I will now close this issue and we can discuss that there. Thanks!

**Comment by KrishnanSG** [comment]
@MrDogeBro thanks for the quick fix. Looking forward to use multiple dark themes which can be set using conf file.
